language: ruby
dist: xenial
before_install:
  # install bundler < 2 because Rails 4.2 is incompatible with bundler >= 2
  - gem install bundler -v '1.17.3'
install: bundle _1.17.3_ install --jobs=2 --retry=2 --path=${BUNDLE_PATH:-vendor/bundle}
cache: bundler
script: bundle exec rake
rvm:
  - 2.5
  - 2.6
  - 2.7
  - ruby-head
env:
  matrix:
    - DEVISE_ORM=active_record
    - DEVISE_ORM=mongoid
services:
  - mongodb
matrix:
  exclude:
    # Skip these combinations because they have incompatible dependencies
    # and will always fail.
    - rvm: 2.6
      gemfile: gemfiles/rails_4.2.gemfile
    - rvm: 2.7
      gemfile: gemfiles/rails_4.2.gemfile
    - rvm: ruby-head
      gemfile: gemfiles/rails_4.2.gemfile
  allow_failures:
    # edge, not expected to pass
    - rvm: ruby-head
    # not supported officially, might cause random failures
    - rvm: 2.7
      gemfile: gemfiles/rails_5.0.gemfile
    - rvm: 2.7
      gemfile: gemfiles/rails_5.1.gemfile
    - rvm: 2.7
      gemfile: gemfiles/rails_5.2.gemfile
gemfile:
  - gemfiles/rails_4.2.gemfile
  - gemfiles/rails_5.0.gemfile
  - gemfiles/rails_5.1.gemfile
  - gemfiles/rails_5.2.gemfile
  - gemfiles/rails_6.0.gemfile
