language: ruby
before_install: gem install bundler -v '1.17.3'
install: bundle _1.17.3_ install --jobs=3 --retry=3
script: bundle exec rake
rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - ruby-head
env:
  matrix:
    - DEVISE_ORM=active_record
    - DEVISE_ORM=mongoid
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: 2.6
      gemfile: gemfiles/rails_4.2_stable.gemfile
gemfile:
  - gemfiles/rails_4.2_stable.gemfile
  - gemfiles/rails_5.0_stable.gemfile
  - gemfiles/rails_5.1_stable.gemfile
  - gemfiles/rails_5.2_stable.gemfile
  - gemfiles/rails_4.2_stable_mongoid.gemfile
  - gemfiles/rails_5.0_stable_mongoid.gemfile
  - gemfiles/rails_5.1_stable_mongoid.gemfile
  - gemfiles/rails_5.2_stable_mongoid.gemfile
